import { Course, Teacher, Batch, Enquiry, TrialRegistration, Student, AttendanceRecord, TestResult, Testimonial, Announcement, StudyMaterial } from './types';

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    grade: 'Class 6 - 8',
    subject: 'Foundation Mathematics',
    description: 'Build strong mathematical fundamentals, problem-solving techniques and arithmetic clarity.',
    batchTiming: 'Mon, Wed, Fri | 4:00 PM - 5:30 PM',
    monthlyFee: '₹1,800 / month',
    availableSeats: 4,
    status: 'Fast Filling',
    highlights: ['Small batch sizes', 'Daily homework check', 'Concept building exercises'],
  },
  {
    id: 'course-2',
    grade: 'Class 6 - 8',
    subject: 'Integrated Science',
    description: 'Practical concept-focused physics, chemistry & biology learning with visual explanations.',
    batchTiming: 'Tue, Thu, Sat | 4:00 PM - 5:30 PM',
    monthlyFee: '₹1,800 / month',
    availableSeats: 6,
    status: 'Open',
    highlights: ['Diagram practice', 'Weekly chapter quizzes', 'Interactive doubt clearing'],
  },
  {
    id: 'course-3',
    grade: 'Class 9 - 10',
    subject: 'Mathematics Special',
    description: 'Rigorous board-oriented practice, NCERT mastery, exemplary problems, and speed calculation tips.',
    batchTiming: 'Mon, Wed, Fri | 5:30 PM - 7:00 PM',
    monthlyFee: '₹2,400 / month',
    availableSeats: 3,
    status: 'Fast Filling',
    highlights: ['Chapter-wise formula sheets', 'Previous 10-year question practice', 'Personalized speed improvement'],
  },
  {
    id: 'course-4',
    grade: 'Class 9 - 10',
    subject: 'Science (Physics & Chemistry)',
    description: 'In-depth conceptual understanding of physical formulas, chemical equations and lab principles.',
    batchTiming: 'Tue, Thu, Sat | 5:30 PM - 7:00 PM',
    monthlyFee: '₹2,400 / month',
    availableSeats: 5,
    status: 'Open',
    highlights: ['Equation balancing sessions', 'Numerical problem solving', 'Fortnightly evaluations'],
  },
  {
    id: 'course-5',
    grade: 'Class 11 - 12',
    subject: 'Senior Mathematics',
    description: 'Calculus, Algebra, and Geometry mastery tailored for CBSE Board Exams & competitive foundation.',
    batchTiming: 'Mon, Wed, Fri | 7:00 PM - 8:30 PM',
    monthlyFee: '₹3,000 / month',
    availableSeats: 2,
    status: 'Fast Filling',
    highlights: ['Advanced calculus modules', 'Individual doubt hours', 'Regular Mock Test Series'],
  },
  {
    id: 'course-6',
    grade: 'Class 11 - 12',
    subject: 'Physics Core',
    description: 'Detailed derivations, numerical mastery and physical conceptual clarity.',
    batchTiming: 'Tue, Thu, Sat | 7:00 PM - 8:30 PM',
    monthlyFee: '₹3,000 / month',
    availableSeats: 4,
    status: 'Open',
    highlights: ['Derivation workbooks', 'Formula application focus', 'Step-by-step guidance'],
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'teacher-1',
    name: 'Rajesh Sharma',
    qualification: 'M.Sc. Mathematics, B.Ed.',
    experience: '12+ Years Teaching Experience',
    subjects: ['Mathematics', 'Reasoning & Aptitude'],
    classesTaught: ['Class 8', 'Class 9', 'Class 10', 'Class 11', 'Class 12'],
    teachingPhilosophy: 'Mathematics is not about memorizing formulas—it is about logical thinking and step-by-step understanding. When students grasp the "why" behind every concept, confidence comes naturally.',
    areasOfExpertise: ['Algebra & Calculus', 'Board Exam Preparation', 'Concept Simplification', 'Speed & Accuracy Training'],
    achievements: ['Guided 400+ students to 90%+ in Board Examinations', 'Recognized for interactive teaching methodologies'],
    photoUrl: '/images/teacher-rajesh.jpg',
    bio: 'Rajesh Sir has been empowering local students in mathematics for over a decade. His methodical approach makes complex mathematical topics straightforward and engaging.',
    studentFeedback: [
      { author: 'Parent of Class 10 Student', comment: 'My son moved from fearing Math to scoring 94% in his mid-terms thanks to Rajesh Sir.', rating: 5 },
      { author: 'Class 12 Student', comment: 'Calculus became my favorite subject after attending Sir\'s classes.', rating: 5 },
    ],
  },
  {
    id: 'teacher-2',
    name: 'Ananya Verma',
    qualification: 'M.Sc. Physics, B.Sc. Chemistry',
    experience: '10+ Years Teaching Experience',
    subjects: ['Physics', 'Chemistry', 'General Science'],
    classesTaught: ['Class 7', 'Class 8', 'Class 9', 'Class 10'],
    teachingPhilosophy: 'Science is surrounding us every day. I believe in relating physical laws and chemical reactions to real-world examples so students stay curious and retain concepts for life.',
    areasOfExpertise: ['Physics Numericals', 'Chemical Equations', 'Diagram & Lab Techniques', 'Doubt Resolution'],
    achievements: ['100% pass record in Class 10 Science Boards', 'Authored concise revision notes for Science'],
    photoUrl: '/images/teacher-ananya.jpg',
    bio: 'Ananya Ma\'am brings energy and practical examples into the science classroom. Her structured revision worksheets help students consistently achieve academic growth.',
    studentFeedback: [
      { author: 'Parent of Class 9 Student', comment: 'Ananya Ma\'am gives personal attention to every child. She regularly updates parents on progress.', rating: 5 },
      { author: 'Class 9 Student', comment: 'Physics numericals used to confuse me, but Ma\'am\'s shortcut steps made them easy.', rating: 5 },
    ],
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch-1',
    name: 'Batch M10-A (Class 10 Math)',
    grade: 'Class 10',
    subject: 'Mathematics',
    teacherId: 'teacher-1',
    teacherName: 'Rajesh Sharma',
    days: 'Mon, Wed, Fri',
    startTime: '5:30 PM',
    endTime: '7:00 PM',
    room: 'Room 101',
    maxStudents: 15,
    enrolledCount: 12,
    status: 'Active',
  },
  {
    id: 'batch-2',
    name: 'Batch S9-B (Class 9 Science)',
    grade: 'Class 9',
    subject: 'Science',
    teacherId: 'teacher-2',
    teacherName: 'Ananya Verma',
    days: 'Tue, Thu, Sat',
    startTime: '5:30 PM',
    endTime: '7:00 PM',
    room: 'Lab 201',
    maxStudents: 15,
    enrolledCount: 10,
    status: 'Active',
  },
  {
    id: 'batch-3',
    name: 'Batch M8-Foundation',
    grade: 'Class 8',
    subject: 'Mathematics',
    teacherId: 'teacher-1',
    teacherName: 'Rajesh Sharma',
    days: 'Mon, Wed, Fri',
    startTime: '4:00 PM',
    endTime: '5:30 PM',
    room: 'Room 102',
    maxStudents: 15,
    enrolledCount: 11,
    status: 'Active',
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-101',
    name: 'Sunil Mehta (Parent)',
    phone: '+91 98112 34567',
    grade: 'Class 10',
    subject: 'Mathematics',
    preferredTiming: 'Evening (5:30 PM)',
    message: 'Looking for coaching for my son Rohan for 10th CBSE Math.',
    createdAt: '2026-09-02T14:30:00Z',
    status: 'Contacted',
    notes: 'Called parent. Scheduled for trial class on Friday.',
  },
  {
    id: 'enq-102',
    name: 'Pooja Sharma',
    phone: '+91 97654 32109',
    grade: 'Class 9',
    subject: 'Science',
    preferredTiming: 'Evening (5:30 PM)',
    message: 'Need help with Physics & Chemistry numericals.',
    createdAt: '2026-09-03T10:15:00Z',
    status: 'New',
    notes: 'New inquiry from website form.',
  },
  {
    id: 'enq-103',
    name: 'Vikram Joshi',
    phone: '+91 98990 12345',
    grade: 'Class 8',
    subject: 'Math & Science',
    preferredTiming: 'Afternoon (4:00 PM)',
    message: 'Interested in combined batch for Class 8.',
    createdAt: '2026-08-30T16:00:00Z',
    status: 'Enrolled',
    notes: 'Trial completed successfully. Enrolled on 1st Sept.',
  },
];

export const INITIAL_TRIALS: TrialRegistration[] = [
  {
    id: 'trial-201',
    studentName: 'Aarav Kumar',
    parentName: 'Ramesh Kumar',
    grade: 'Class 10',
    subject: 'Mathematics',
    phone: '+91 98450 99887',
    whatsapp: '+91 98450 99887',
    preferredTiming: 'Mon, Wed, Fri (5:30 PM)',
    preferredTeacher: 'Rajesh Sharma',
    trialDate: '2026-09-05',
    status: 'Scheduled',
    createdAt: '2026-09-03T09:20:00Z',
    notes: 'Confirmed via WhatsApp.',
  },
  {
    id: 'trial-202',
    studentName: 'Sneha Patel',
    parentName: 'Kiran Patel',
    grade: 'Class 9',
    subject: 'Science',
    phone: '+91 98760 11223',
    whatsapp: '+91 98760 11223',
    preferredTiming: 'Tue, Thu, Sat (5:30 PM)',
    preferredTeacher: 'Ananya Verma',
    trialDate: '2026-09-04',
    status: 'Attended',
    createdAt: '2026-09-01T11:45:00Z',
    notes: 'Student enjoyed the Physics diagram demo.',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    studentName: 'Rohan Mehta',
    parentName: 'Sunil Mehta',
    grade: 'Class 10',
    subjects: ['Mathematics'],
    phone: '+91 98112 34567',
    whatsapp: '+91 98112 34567',
    batchId: 'batch-1',
    batchName: 'Batch M10-A (Class 10 Math)',
    teacherName: 'Rajesh Sharma',
    admissionDate: '2026-06-15',
    status: 'Active',
  },
  {
    id: 'std-2',
    studentName: 'Sneha Patel',
    parentName: 'Kiran Patel',
    grade: 'Class 9',
    subjects: ['Science'],
    phone: '+91 98760 11223',
    whatsapp: '+91 98760 11223',
    batchId: 'batch-2',
    batchName: 'Batch S9-B (Class 9 Science)',
    teacherName: 'Ananya Verma',
    admissionDate: '2026-07-01',
    status: 'Active',
  },
  {
    id: 'std-3',
    studentName: 'Aditya Joshi',
    parentName: 'Vikram Joshi',
    grade: 'Class 8',
    subjects: ['Mathematics', 'Science'],
    phone: '+91 98990 12345',
    whatsapp: '+91 98990 12345',
    batchId: 'batch-3',
    batchName: 'Batch M8-Foundation',
    teacherName: 'Rajesh Sharma',
    admissionDate: '2026-09-01',
    status: 'Active',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', studentId: 'std-1', studentName: 'Rohan Mehta', batchId: 'batch-1', date: '2026-09-01', status: 'Present' },
  { id: 'att-2', studentId: 'std-1', studentName: 'Rohan Mehta', batchId: 'batch-1', date: '2026-09-03', status: 'Present' },
  { id: 'att-3', studentId: 'std-2', studentName: 'Sneha Patel', batchId: 'batch-2', date: '2026-09-02', status: 'Present' },
  { id: 'att-4', studentId: 'std-3', studentName: 'Aditya Joshi', batchId: 'batch-3', date: '2026-09-01', status: 'Present' },
];

export const INITIAL_TEST_RESULTS: TestResult[] = [
  {
    id: 'test-1',
    testName: 'Unit Test 1 - Quadratic Equations',
    subject: 'Mathematics',
    studentId: 'std-1',
    studentName: 'Rohan Mehta',
    grade: 'Class 10',
    date: '2026-08-28',
    maxMarks: 50,
    marksObtained: 44,
    percentage: 88,
    remarks: 'Excellent concept clarity in factorization methods.',
  },
  {
    id: 'test-2',
    testName: 'Monthly Assessment - Light & Reflection',
    subject: 'Science',
    studentId: 'std-2',
    studentName: 'Sneha Patel',
    grade: 'Class 9',
    date: '2026-08-25',
    maxMarks: 50,
    marksObtained: 42,
    percentage: 84,
    remarks: 'Good diagram neatness and ray tracing accuracy.',
  },
  {
    id: 'test-3',
    testName: 'Algebra Basics Quiz',
    subject: 'Mathematics',
    studentId: 'std-3',
    studentName: 'Aditya Joshi',
    grade: 'Class 8',
    date: '2026-08-30',
    maxMarks: 25,
    marksObtained: 22,
    percentage: 88,
    remarks: 'Very quick calculations.',
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'testim-1',
    name: 'Suresh & Priya Nair',
    role: 'Parents of Class 10 Student',
    grade: 'Class 10 CBSE',
    rating: 5,
    content: 'Prime Learning has been a game-changer for our son. The teachers focus on building concepts rather than mindless memorization. Regular test feedback keeps us completely informed.',
    isSample: true,
  },
  {
    id: 'testim-2',
    name: 'Kavita Deshmukh',
    role: 'Parent of Class 9 Student',
    grade: 'Class 9 Science',
    rating: 5,
    content: 'Small batch size makes a huge difference. Ananya Ma\'am gives personal attention and cleared all doubts before school mid-terms. Highly recommended local institute.',
    isSample: true,
  },
  {
    id: 'testim-3',
    name: 'Rahul V.',
    role: 'Class 12 Student',
    grade: 'Class 12 Math',
    rating: 5,
    content: 'Rajesh Sir\'s teaching style is clear and easy to follow. The trial class convinced me to join, and my calculus marks improved significantly.',
    isSample: true,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Mid-Term Board Mock Test Schedule',
    content: 'Class 10 Mathematics Board pattern Mock Test will be held on Sunday, Sept 14th from 9:00 AM to 12:00 PM.',
    date: '2026-09-02',
    targetGrade: 'Class 10',
    author: 'Rajesh Sharma',
  },
  {
    id: 'anc-2',
    title: 'Science Practical Worksheet Distributed',
    content: 'All Class 9 Science students can download the Physics Ray Diagram Practice Worksheet from the student dashboard.',
    date: '2026-09-01',
    targetGrade: 'Class 9',
    author: 'Ananya Verma',
  },
];

export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    title: 'Class 10 Math Formula Cheat Sheet',
    subject: 'Mathematics',
    grade: 'Class 10',
    fileType: 'PDF Document',
    downloadUrl: '#',
    date: '2026-08-30',
  },
  {
    id: 'mat-2',
    title: 'Class 9 Physics Work & Energy Solved Numericals',
    subject: 'Science',
    grade: 'Class 9',
    fileType: 'PDF Document',
    downloadUrl: '#',
    date: '2026-08-28',
  },
];
