import { Course, Teacher, Batch, Enquiry, TrialRegistration, Student, AttendanceRecord, TestResult, Testimonial, Announcement, StudyMaterial } from './types';

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-12-math',
    grade: 'Class 12',
    subject: 'Only Mathematics',
    description: 'Senior Secondary Mathematics: Calculus, Vectors, 3D Geometry, Algebra & CBSE Board exam prep.',
    batchTiming: 'Mon, Wed, Fri | 6:30 PM - 8:00 PM',
    monthlyFee: '₹3,500 / month',
    availableSeats: 3,
    status: 'Fast Filling',
    highlights: ['Calculus & Board Paper prep', '10-year previous questions', 'Mon, Wed, Fri schedule'],
  },
  {
    id: 'course-11-math',
    grade: 'Class 11',
    subject: 'Only Mathematics',
    description: 'Calculus foundation, Trigonometry, Sets, Functions & Complex Numbers for Class 11.',
    batchTiming: 'Tue, Thu, Sat | 6:30 PM - 8:00 PM',
    monthlyFee: '₹3,000 / month',
    availableSeats: 4,
    status: 'Open',
    highlights: ['Trigonometry & Algebra mastery', 'Step-by-step doubt clearing', 'Tue, Thu, Sat schedule'],
  },
  {
    id: 'course-10-combo',
    grade: 'Class 10',
    subject: 'Maths & Science (Combined)',
    description: 'Complete 10th CBSE Board prep: Mathematics + Physics, Chemistry & Biology combined batch.',
    batchTiming: 'Mon to Sat (Alternate Days) | 5:00 PM - 6:30 PM',
    monthlyFee: '₹5,000 / month',
    availableSeats: 2,
    status: 'Fast Filling',
    highlights: ['Maths + Science complete coverage', 'NCERT & Exemplar problem solving', 'Mon-Sat alternate days'],
  },
  {
    id: 'course-10-single',
    grade: 'Class 10',
    subject: 'Single Subject (Maths or Science)',
    description: 'Focus on either Class 10 Mathematics or Class 10 Science individually.',
    batchTiming: 'Mon to Sat (Alternate Days) | 5:00 PM - 6:30 PM',
    monthlyFee: '₹3,000 / month',
    availableSeats: 5,
    status: 'Open',
    highlights: ['Single subject focus', 'Individual attention', 'Alternate day classes'],
  },
  {
    id: 'course-9-combo',
    grade: 'Class 9',
    subject: 'Maths & Science (Combined)',
    description: 'Strong foundation for 9th grade Mathematics, Physics, Chemistry & Biology.',
    batchTiming: 'Mon to Sat (Alternate Days) | 5:00 PM - 6:30 PM',
    monthlyFee: '₹4,500 / month',
    availableSeats: 4,
    status: 'Open',
    highlights: ['Maths + Science complete prep', 'Diagram practice & numericals', 'Mon-Sat alternate days'],
  },
  {
    id: 'course-9-single',
    grade: 'Class 9',
    subject: 'Single Subject (Maths or Science)',
    description: 'In-depth guidance for either Class 9 Mathematics or Class 9 Science.',
    batchTiming: 'Mon to Sat (Alternate Days) | 5:00 PM - 6:30 PM',
    monthlyFee: '₹2,500 / month',
    availableSeats: 6,
    status: 'Open',
    highlights: ['Subject-wise deep dive', 'Weekly practice quizzes', 'Alternate day classes'],
  },
  {
    id: 'course-8-combo',
    grade: 'Class 8',
    subject: 'Maths & Science (Combined)',
    description: 'Middle school foundation in Algebra, Geometry, Physics & Chemistry.',
    batchTiming: 'Mon to Sat (Alternate Days) | 4:00 PM - 5:30 PM',
    monthlyFee: '₹4,000 / month',
    availableSeats: 5,
    status: 'Open',
    highlights: ['Combined Maths & Science', 'Concept building exercises', 'Mon-Sat alternate days'],
  },
  {
    id: 'course-8-single',
    grade: 'Class 8',
    subject: 'Single Subject (Maths or Science)',
    description: 'Individual coaching for either Class 8 Mathematics or Class 8 Science.',
    batchTiming: 'Mon to Sat (Alternate Days) | 4:00 PM - 5:30 PM',
    monthlyFee: '₹2,200 / month',
    availableSeats: 5,
    status: 'Open',
    highlights: ['Single subject coaching', 'Daily homework check', 'Alternate day classes'],
  },
  {
    id: 'course-7-combo',
    grade: 'Class 7',
    subject: 'Maths & Science (Combined)',
    description: 'Building arithmetic, fundamental algebra, physics & chemistry clarity.',
    batchTiming: 'Mon to Sat (Alternate Days) | 4:00 PM - 5:30 PM',
    monthlyFee: '₹3,500 / month',
    availableSeats: 6,
    status: 'Open',
    highlights: ['Combined subject tutoring', 'Small batch environment', 'Mon-Sat alternate days'],
  },
  {
    id: 'course-7-single',
    grade: 'Class 7',
    subject: 'Single Subject (Maths or Science)',
    description: 'Focused tuition for Class 7 Mathematics or Science.',
    batchTiming: 'Mon to Sat (Alternate Days) | 4:00 PM - 5:30 PM',
    monthlyFee: '₹2,100 / month',
    availableSeats: 6,
    status: 'Open',
    highlights: ['Single subject mastery', 'Personalized guidance', 'Alternate day classes'],
  },
  {
    id: 'course-6-combo',
    grade: 'Class 6',
    subject: 'Maths & Science (Combined)',
    description: 'Foundational transition coaching for Class 6 Mathematics and General Science.',
    batchTiming: 'Mon to Sat (Alternate Days) | 3:30 PM - 5:00 PM',
    monthlyFee: '₹3,000 / month',
    availableSeats: 5,
    status: 'Open',
    highlights: ['Maths + Science foundational learning', 'Interactive activities', 'Mon-Sat alternate days'],
  },
  {
    id: 'course-primary',
    grade: 'Class 1 - 5 (Primary)',
    subject: 'Maths, Science, English, Social Science',
    description: 'Daily foundational tutoring in 4 core subjects (2 subjects taught daily, 6 days a week).',
    batchTiming: 'Monday to Saturday (6 Days/Wk) | 3:30 PM - 5:30 PM',
    monthlyFee: '₹2,500 / month',
    availableSeats: 6,
    status: 'Open',
    highlights: ['2 Subjects Daily (Mon-Sat)', 'Maths, Science, English, SST', 'Fun learning & homework help'],
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'teacher-praveen',
    name: 'Praveen Gandhi',
    qualification: 'M.Sc. Mathematics, B.Ed.',
    experience: '12+ Years Teaching Experience',
    subjects: ['Mathematics (Class 6 to 12)', 'Reasoning & Aptitude'],
    classesTaught: ['Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10', 'Class 11', 'Class 12'],
    teachingPhilosophy: 'Mathematics is not about memorizing formulas—it is about logical thinking and step-by-step understanding. When students grasp the "why" behind every concept, confidence comes naturally.',
    areasOfExpertise: ['Algebra & Calculus', 'CBSE Board Exam Preparation', 'Concept Simplification', 'Speed & Accuracy Training'],
    achievements: ['Guided 400+ students to 90%+ in Board Examinations', 'Recognized for interactive step-by-step teaching methodologies'],
    photoUrl: '/images/teacher-rajesh.jpg',
    bio: 'Praveen Gandhi Sir has been empowering local students in Mathematics for over a decade. His methodical approach makes complex mathematical topics straightforward and engaging.',
    studentFeedback: [
      { author: 'Parent of Class 10 Student', comment: 'My son moved from fearing Math to scoring 94% in his mid-terms thanks to Praveen Sir.', rating: 5 },
      { author: 'Class 12 Student', comment: 'Calculus became my favorite subject after attending Praveen Sir\'s classes.', rating: 5 },
    ],
  },
  {
    id: 'teacher-rashmi',
    name: 'Rashmi Anand',
    qualification: 'M.Sc. Science, B.Sc. Education',
    experience: '10+ Years Teaching Experience',
    subjects: ['Science (Physics, Chemistry, Biology)', 'Primary All Subjects (Class 1-5)'],
    classesTaught: ['Class 1-5 (Primary All Subjects)', 'Class 6-10 (Science)'],
    teachingPhilosophy: 'Science surrounds us every day. I believe in relating physical laws, chemical reactions, and natural concepts to real-world examples so students stay curious and retain concepts for life.',
    areasOfExpertise: ['Physics & Chemistry Numericals', 'Chemical Equations', 'Diagram & Lab Techniques', 'Primary Foundational Learning'],
    achievements: ['100% pass record in Class 10 Science Boards', 'Authored concise revision notes for Science & Primary Learning'],
    photoUrl: '/images/teacher-ananya.jpg',
    bio: 'Rashmi Anand Ma\'am brings high energy and practical real-life examples into the science and primary classrooms. Her structured revision worksheets help students consistently achieve academic growth.',
    studentFeedback: [
      { author: 'Parent of Class 9 Student', comment: 'Rashmi Ma\'am gives personal attention to every child. She regularly updates parents on progress.', rating: 5 },
      { author: 'Class 9 Student', comment: 'Science numericals used to confuse me, but Rashmi Ma\'am\'s shortcut steps made them easy.', rating: 5 },
    ],
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch-12m',
    name: 'Class 12 Mathematics Batch',
    grade: 'Class 12',
    subject: 'Mathematics',
    teacherId: 'teacher-praveen',
    teacherName: 'Praveen Gandhi',
    days: 'Mon, Wed, Fri',
    startTime: '6:30 PM',
    endTime: '8:00 PM',
    room: 'Room 101',
    maxStudents: 15,
    enrolledCount: 12,
    status: 'Active',
  },
  {
    id: 'batch-11m',
    name: 'Class 11 Mathematics Batch',
    grade: 'Class 11',
    subject: 'Mathematics',
    teacherId: 'teacher-praveen',
    teacherName: 'Praveen Gandhi',
    days: 'Tue, Thu, Sat',
    startTime: '6:30 PM',
    endTime: '8:00 PM',
    room: 'Room 101',
    maxStudents: 15,
    enrolledCount: 11,
    status: 'Active',
  },
  {
    id: 'batch-10combo',
    name: 'Class 10 Maths & Science Combo',
    grade: 'Class 10',
    subject: 'Maths & Science',
    teacherId: 'teacher-praveen',
    teacherName: 'Praveen Gandhi & Rashmi Anand',
    days: 'Mon to Sat (Alternate Days)',
    startTime: '5:00 PM',
    endTime: '6:30 PM',
    room: 'Room 102',
    maxStudents: 15,
    enrolledCount: 13,
    status: 'Active',
  },
  {
    id: 'batch-9combo',
    name: 'Class 9 Maths & Science Combo',
    grade: 'Class 9',
    subject: 'Maths & Science',
    teacherId: 'teacher-rashmi',
    teacherName: 'Praveen Gandhi & Rashmi Anand',
    days: 'Mon to Sat (Alternate Days)',
    startTime: '5:00 PM',
    endTime: '6:30 PM',
    room: 'Lab 201',
    maxStudents: 15,
    enrolledCount: 11,
    status: 'Active',
  },
  {
    id: 'batch-8combo',
    name: 'Class 8 Maths & Science Combo',
    grade: 'Class 8',
    subject: 'Maths & Science',
    teacherId: 'teacher-praveen',
    teacherName: 'Praveen Gandhi & Rashmi Anand',
    days: 'Mon to Sat (Alternate Days)',
    startTime: '4:00 PM',
    endTime: '5:30 PM',
    room: 'Room 103',
    maxStudents: 15,
    enrolledCount: 10,
    status: 'Active',
  },
  {
    id: 'batch-primary',
    name: 'Primary (Class 1-5) Foundational Batch',
    grade: 'Class 1 - 5',
    subject: 'Maths, Science, English, SST',
    teacherId: 'teacher-rashmi',
    teacherName: 'Rashmi Anand',
    days: 'Mon to Sat (6 Days/Week)',
    startTime: '3:30 PM',
    endTime: '5:30 PM',
    room: 'Junior Lab',
    maxStudents: 15,
    enrolledCount: 9,
    status: 'Active',
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-101',
    name: 'Sunil Mehta (Parent)',
    phone: '+91 98109 89437',
    grade: 'Class 10',
    subject: 'Maths & Science',
    preferredTiming: 'Evening (5:00 PM)',
    message: 'Looking for Class 10 Maths & Science combined batch (₹5,000/mo).',
    createdAt: '2026-09-02T14:30:00Z',
    status: 'Contacted',
    notes: 'Called parent. Scheduled trial class.',
  },
  {
    id: 'enq-102',
    name: 'Pooja Sharma',
    phone: '+91 93509 57765',
    grade: 'Class 12',
    subject: 'Mathematics',
    preferredTiming: 'Mon, Wed, Fri (6:30 PM)',
    message: 'Interested in Class 12 Maths batch with Praveen Sir (₹3,500/mo).',
    createdAt: '2026-09-03T10:15:00Z',
    status: 'New',
    notes: 'New inquiry from website form.',
  },
];

export const INITIAL_TRIALS: TrialRegistration[] = [
  {
    id: 'trial-201',
    studentName: 'Aarav Kumar',
    parentName: 'Ramesh Kumar',
    grade: 'Class 10',
    subject: 'Maths & Science',
    phone: '+91 98109 89437',
    whatsapp: '+91 98109 89437',
    preferredTiming: 'Mon to Sat (Alternate Days)',
    preferredTeacher: 'Praveen Gandhi',
    trialDate: '2026-09-05',
    status: 'Scheduled',
    createdAt: '2026-09-03T09:20:00Z',
    notes: 'Confirmed via WhatsApp.',
  },
  {
    id: 'trial-202',
    studentName: 'Sneha Patel',
    parentName: 'Kiran Patel',
    grade: 'Class 4',
    subject: 'Primary All Subjects',
    phone: '+91 93509 57765',
    whatsapp: '+91 93509 57765',
    preferredTiming: 'Mon to Sat (6 Days/Wk)',
    preferredTeacher: 'Rashmi Anand',
    trialDate: '2026-09-04',
    status: 'Attended',
    createdAt: '2026-09-01T11:45:00Z',
    notes: 'Attended primary demo with Rashmi Ma\'am.',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    studentName: 'Rohan Mehta',
    parentName: 'Sunil Mehta',
    grade: 'Class 10',
    subjects: ['Maths & Science'],
    phone: '+91 98109 89437',
    whatsapp: '+91 98109 89437',
    batchId: 'batch-10combo',
    batchName: 'Class 10 Maths & Science Combo',
    teacherName: 'Praveen Gandhi & Rashmi Anand',
    admissionDate: '2026-06-15',
    status: 'Active',
  },
  {
    id: 'std-2',
    studentName: 'Sneha Patel',
    parentName: 'Kiran Patel',
    grade: 'Class 12',
    subjects: ['Mathematics'],
    phone: '+91 93509 57765',
    whatsapp: '+91 93509 57765',
    batchId: 'batch-12m',
    batchName: 'Class 12 Mathematics Batch',
    teacherName: 'Praveen Gandhi',
    admissionDate: '2026-07-01',
    status: 'Active',
  },
  {
    id: 'std-3',
    studentName: 'Aditya Joshi',
    parentName: 'Vikram Joshi',
    grade: 'Class 4',
    subjects: ['Maths, Science, English, SST'],
    phone: '+91 98990 12345',
    whatsapp: '+91 98990 12345',
    batchId: 'batch-primary',
    batchName: 'Primary (Class 1-5) Foundational Batch',
    teacherName: 'Rashmi Anand',
    admissionDate: '2026-09-01',
    status: 'Active',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', studentId: 'std-1', studentName: 'Rohan Mehta', batchId: 'batch-10combo', date: '2026-09-01', status: 'Present' },
  { id: 'att-2', studentId: 'std-1', studentName: 'Rohan Mehta', batchId: 'batch-10combo', date: '2026-09-03', status: 'Present' },
  { id: 'att-3', studentId: 'std-2', studentName: 'Sneha Patel', batchId: 'batch-12m', date: '2026-09-02', status: 'Present' },
  { id: 'att-4', studentId: 'std-3', studentName: 'Aditya Joshi', batchId: 'batch-primary', date: '2026-09-01', status: 'Present' },
];

export const INITIAL_TEST_RESULTS: TestResult[] = [
  {
    id: 'test-1',
    testName: 'Unit Test 1 - Quadratic Equations',
    subject: 'Mathematics',
    studentId: 'std-1',
    studentName: 'Rohan Mehta',
    grade: 'Class 10',
    date: '2026-08-28',
    maxMarks: 50,
    marksObtained: 44,
    percentage: 88,
    remarks: 'Excellent concept clarity in factorization methods.',
  },
  {
    id: 'test-2',
    testName: 'Calculus Integration Mock Test',
    subject: 'Mathematics',
    studentId: 'std-2',
    studentName: 'Sneha Patel',
    grade: 'Class 12',
    date: '2026-08-25',
    maxMarks: 50,
    marksObtained: 45,
    percentage: 90,
    remarks: 'Great step precision by Praveen Sir\'s methodology.',
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'testim-1',
    name: 'Suresh & Priya Nair',
    role: 'Parents of Class 10 Student',
    grade: 'Class 10 CBSE',
    rating: 5,
    content: 'Prime Learning Classes has been a game-changer for our son. Praveen Sir and Rashmi Ma\'am focus on building concepts rather than mindless memorization.',
    isSample: true,
  },
  {
    id: 'testim-2',
    name: 'Kavita Deshmukh',
    role: 'Parent of Primary Student',
    grade: 'Class 4 All Subjects',
    rating: 5,
    content: 'Rashmi Ma\'am teaches 2 subjects daily for 6 days a week. The personal attention has significantly improved my daughter\'s fundamentals.',
    isSample: true,
  },
  {
    id: 'testim-3',
    name: 'Rahul V.',
    role: 'Class 12 Student',
    grade: 'Class 12 Math',
    rating: 5,
    content: 'Praveen Sir\'s teaching style is clear and easy to follow. Mon, Wed, Fri batch schedule fits perfectly, and my calculus marks improved immensely.',
    isSample: true,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Mid-Term Board Mock Test Schedule',
    content: 'Class 10 & 12 Mathematics Board pattern Mock Test will be held on Sunday, Sept 14th from 9:00 AM to 12:00 PM.',
    date: '2026-09-02',
    targetGrade: 'Class 10 & 12',
    author: 'Praveen Gandhi',
  },
  {
    id: 'anc-2',
    title: 'Primary 6-Day Weekly Worksheet Distributed',
    content: 'Class 1-5 students can download the weekly Maths & Science revision worksheet from the student dashboard.',
    date: '2026-09-01',
    targetGrade: 'Class 1 - 5',
    author: 'Rashmi Anand',
  },
];

export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    title: 'Class 12 Calculus & Vectors Formula Sheet',
    subject: 'Mathematics',
    grade: 'Class 12',
    fileType: 'PDF Document',
    downloadUrl: '#',
    date: '2026-08-30',
  },
  {
    id: 'mat-2',
    title: 'Class 10 Science Chemical Equations & Numericals Worksheet',
    subject: 'Science',
    grade: 'Class 10',
    fileType: 'PDF Document',
    downloadUrl: '#',
    date: '2026-08-28',
  },
];
